import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navigation from "@/components/navigation";
import { Providers } from "./providers";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Regular (400), Medium (500), Bold (700)
});

export const metadata: Metadata = {
  title: "PT. Tujuh Anugrah Abadi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} antialiased`}>
        <Navigation />
          <Providers>
            {children}
          </Providers>
        <Footer />
      </body>
    </html>
  );
}
